baseurl = "https://yutarot.me/"
languageCode = "ja_JP.UTF-8"
title = "日々雑感"
theme = "pickles"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2018 yutarot"
enableGitInfo = true

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
#  twitter = "Your Twitter username"
#  facebook = "Your Facebook username"
  instagram = "yutarot_binfish"
#  googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "yutarot"
#  gitlab = "Your GitLab username"
#  npm = "Your npm username"
  codepen = "yutarot"
#  dribbble = "Your Dribbble username"
#  fivehundredpx = "Your 500px username" # 500px
#  flickr = "Your Flickr username"
#  pinterest = "Your Pinterest username"
#  tumblr = "Your Tumblr username"
#  vimeo = "Your Vimeo username"
#  youtube = "Your YouTube username"
#  linkedin = "Your LinkedIn username"
#  # Disqus shortname
#  disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-82631162-4"
  author = "yutarot"
  authorwebsite = "https://blog.binfish.jp"
  avatar = "https://s.gravatar.com/avatar/b8a2df8309205145a88664926e17ac43?s=200"
  contact = "mailto:takenoco88@gmail.com"
  bio = "燃料びーるのうぇっぶえんじにゃー"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "a.k.a ポエム"
  # Logo image. This is displayed ogp image.
  #logo = "/path/to/logo"
  #favicon = "/path/to/favicon"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "https://blog.binfish.jp"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

#  [[related.indices]]
#  name = "keywords"
#  weight = 150
#  [[related.indices]]
#  name  = "author"
#  toLower = true
#  weight = 30
#  [[related.indices]]
#  name  = "tags"
#  weight = 100
#  [[related.indices]]
#  name  = "date"
#  weight = 10
#  pattern = "2017"
